import AppKit
let size = CGSize(width: 1024, height: 1024)
let image = NSImage(size: size)
image.lockFocus()
NSColor(calibratedRed: 0.97, green: 0.95, blue: 0.90, alpha: 1).setFill()
NSBezierPath(rect: CGRect(origin: .zero, size: size)).fill()
let ink = NSColor(calibratedRed: 0.76, green: 0.34, blue: 0.24, alpha: 1)
ink.setStroke()
let camera = NSBezierPath(roundedRect: CGRect(x: 185, y: 245, width: 654, height: 490), xRadius: 95, yRadius: 95)
camera.lineWidth = 35; camera.stroke()
let top = NSBezierPath(); top.move(to: CGPoint(x: 330, y: 740)); top.line(to: CGPoint(x: 375, y: 795)); top.line(to: CGPoint(x: 515, y: 795)); top.line(to: CGPoint(x: 560, y: 740)); top.lineWidth = 35; top.lineJoinStyle = .round; top.stroke()
let lens = NSBezierPath(ovalIn: CGRect(x: 360, y: 345, width: 265, height: 265)); lens.lineWidth = 30; lens.stroke()
ink.setFill(); NSBezierPath(ovalIn: CGRect(x: 715, y: 640, width: 38, height: 38)).fill()
NSColor(calibratedRed: 0.97, green: 0.95, blue: 0.90, alpha: 1).setStroke()
let pen = NSBezierPath(); pen.move(to: CGPoint(x: 570, y: 190)); pen.line(to: CGPoint(x: 828, y: 468)); pen.lineWidth = 95; pen.lineCapStyle = .round; pen.stroke()
ink.setStroke(); pen.lineWidth = 49; pen.stroke()
image.unlockFocus()
let bitmap = NSBitmapImageRep(data: image.tiffRepresentation!)!
try bitmap.representation(using: .png, properties: [:])!.write(to: URL(fileURLWithPath: CommandLine.arguments[1]))
